package vistas;

import DAO.DAOFactory;
import Modelo.Enfermera;
import java.awt.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Gustavo Rodriguez
 */
public class Agregar_Enfermera extends javax.swing.JFrame {

    private DAOFactory MDC;

    public Agregar_Enfermera() {
        initComponents();
        setLocationRelativeTo(null);
        DAOFactory MDC = DAOFactory.getDAOFactory(1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        t_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_cc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_dir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t_usuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t_contra = new javax.swing.JTextField();
        edad = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        depart = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        ciudad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/fondo.jpg"))); // NOI18N
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        t_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_nombreKeyTyped(evt);
            }
        });
        panel1.add(t_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 97, 650, -1));

        jLabel3.setText("C.C");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        t_cc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_ccKeyTyped(evt);
            }
        });
        panel1.add(t_cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 123, 268, -1));

        jLabel4.setText("Telefono:");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 126, -1, -1));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        panel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 123, 290, -1));

        jLabel5.setText("Dirección:");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));
        panel1.add(t_dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 154, 268, -1));

        jLabel6.setText("Correo:");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 157, -1, -1));
        panel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 154, 290, -1));

        jLabel7.setText("Departamento:");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel8.setText("Edad:");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabel9.setText("Usuario:");
        panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        t_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_usuarioKeyTyped(evt);
            }
        });
        panel1.add(t_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 230, 270, -1));

        jLabel10.setText("Contraseña:");
        panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));
        panel1.add(t_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 230, 286, -1));

        edad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21" }));
        panel1.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 270, 60, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        panel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 348, -1, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 348, -1, -1));

        panel1.add(depart, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 190, 270, -1));

        jLabel11.setText("Ciudad:");
        panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        panel1.add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 290, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void t_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nombreKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A') | c > 'Z') {
            evt.consume();
        }
    }//GEN-LAST:event_t_nombreKeyTyped

    private void t_ccKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_ccKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_t_ccKeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_jTextField4KeyTyped

    private void t_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_usuarioKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A') | c > 'Z') {
            evt.consume();
        }
    }//GEN-LAST:event_t_usuarioKeyTyped

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        if (t_nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese nombre");
        } else if (t_cc.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese Cedula");
        } else if (t_usuario.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese Usuario");
        } else if (t_contra.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese Contraseña");
        } else {
            try {
                if (MDC.getDAOEnfermera().consultarEnfermera(Integer.parseInt(t_cc.getText())).getCC() == Integer.parseInt(t_cc.getText())) {
                    JOptionPane.showMessageDialog(rootPane, "Ya existe una Enfermera con esta identificación, debe digitar una identificación distinta");
                } else {
                    try {
                        Enfermera enfermeraNueva = new Enfermera();
                        enfermeraNueva.SetCC(Integer.parseInt(t_cc.getText()));
                        enfermeraNueva.SetNombre(t_nombre.getText());
                        enfermeraNueva.SetUsuario(t_usuario.getText());
                        enfermeraNueva.SetContraseña(enfermeraNueva.md5(t_contra.getText()));

                        MDC.getDAOEnfermera().insertarEnfermera(enfermeraNueva);
                        JOptionPane.showMessageDialog(rootPane, "Inserto Satisfactoriamente");
                        Principal_administrador PA = new Principal_administrador();
                        PA.setVisible(true);
                        dispose();

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, "Error al insertar la enfermera");
                    }

                }
                /*
                 */
            } catch (Exception ex) {
                Logger.getLogger(Agregar_Administrador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Enfermera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ciudad;
    private javax.swing.JComboBox<String> depart;
    private javax.swing.JComboBox<String> edad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private org.edisoncor.gui.panel.Panel panel1;
    private javax.swing.JTextField t_cc;
    private javax.swing.JTextField t_contra;
    private javax.swing.JTextField t_dir;
    private javax.swing.JTextField t_nombre;
    private javax.swing.JTextField t_usuario;
    // End of variables declaration//GEN-END:variables
}
