package vistas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gustavo Rodriguez
 */
public class opciones_enfermera extends javax.swing.JFrame {

    /**
     * Creates new form opciones_enfermera
     */
    public opciones_enfermera() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        btnRegresar = new javax.swing.JButton();
        btnAgregarPaciente = new javax.swing.JButton();
        btnConsultarPaciente = new javax.swing.JButton();
        btnModificarPaciente = new javax.swing.JButton();
        btnEliminarPaciente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/fondo.jpg"))); // NOI18N

        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        btnAgregarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/agregar usuario.png"))); // NOI18N
        btnAgregarPaciente.setText("Agregar Pacientes");
        btnAgregarPaciente.setContentAreaFilled(false);
        btnAgregarPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarPaciente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAgregarPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarPacienteMouseClicked(evt);
            }
        });

        btnConsultarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Lupa.jpg"))); // NOI18N
        btnConsultarPaciente.setText("Consultar Pacientes");
        btnConsultarPaciente.setContentAreaFilled(false);
        btnConsultarPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultarPaciente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConsultarPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarPacienteMouseClicked(evt);
            }
        });

        btnModificarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/modificar usuario.png"))); // NOI18N
        btnModificarPaciente.setText("Modificar pacientes");
        btnModificarPaciente.setContentAreaFilled(false);
        btnModificarPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarPaciente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnModificarPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarPacienteMouseClicked(evt);
            }
        });

        btnEliminarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/eliminar_1.jpg"))); // NOI18N
        btnEliminarPaciente.setText("Eliminar Pacientes");
        btnEliminarPaciente.setContentAreaFilled(false);
        btnEliminarPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarPaciente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEliminarPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarPacienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btnEliminarPaciente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnAgregarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar)
                    .addComponent(btnConsultarPaciente))
                .addGap(0, 396, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAgregarPaciente)
                        .addComponent(btnModificarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConsultarPaciente))
                .addGap(39, 39, 39)
                .addComponent(btnEliminarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPacienteMouseClicked
        // TODO add your handling code here:
        Agregar_pacientes Ap = new Agregar_pacientes();
        Ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgregarPacienteMouseClicked

    private void btnModificarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarPacienteMouseClicked
        // TODO add your handling code here:
        Modificar_paciente Mp =new Modificar_paciente();
        Mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModificarPacienteMouseClicked

    private void btnConsultarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarPacienteMouseClicked
        // TODO add your handling code here:
        Consultar_paciente Cp = new Consultar_paciente();
        Cp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnConsultarPacienteMouseClicked

    private void btnEliminarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPacienteMouseClicked
        // TODO add your handling code here:
        Eliminar_paciente Ep= new Eliminar_paciente();
        Ep.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEliminarPacienteMouseClicked

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        Principal_Enfermera PE = new Principal_Enfermera();
        PE.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opciones_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opciones_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opciones_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opciones_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new opciones_enfermera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPaciente;
    private javax.swing.JButton btnConsultarPaciente;
    private javax.swing.JButton btnEliminarPaciente;
    private javax.swing.JButton btnModificarPaciente;
    private javax.swing.JButton btnRegresar;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
