package vistas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gustavo Rodriguez
 */
public class Opciones_administrador extends javax.swing.JFrame {

    /**
     * Creates new form Opciones_administrador
     */
    public Opciones_administrador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        btnEliminarDiagnstico = new javax.swing.JButton();
        btnaddDiag = new javax.swing.JButton();
        btnConsultar_Enfermera = new javax.swing.JButton();
        btnModificarEnfermera = new javax.swing.JButton();
        btnAgregarEnfermera = new javax.swing.JButton();
        btnBorrarEnfermera = new javax.swing.JButton();
        btnModfiDiagnostico = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/fondo.jpg"))); // NOI18N

        btnEliminarDiagnstico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/delete.png"))); // NOI18N
        btnEliminarDiagnstico.setText("Eliminar Diagnostico");
        btnEliminarDiagnstico.setContentAreaFilled(false);
        btnEliminarDiagnstico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarDiagnstico.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEliminarDiagnstico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarDiagnstico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDiagnsticoActionPerformed(evt);
            }
        });

        btnaddDiag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/agregar.png"))); // NOI18N
        btnaddDiag.setText("Agregar Diagnostico");
        btnaddDiag.setContentAreaFilled(false);
        btnaddDiag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnaddDiag.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnaddDiag.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnaddDiag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddDiagMouseClicked(evt);
            }
        });

        btnConsultar_Enfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Lupa.jpg"))); // NOI18N
        btnConsultar_Enfermera.setText(" Consultar Enfermera");
        btnConsultar_Enfermera.setToolTipText("");
        btnConsultar_Enfermera.setContentAreaFilled(false);
        btnConsultar_Enfermera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar_Enfermera.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConsultar_Enfermera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar_Enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultar_EnfermeraMouseClicked(evt);
            }
        });

        btnModificarEnfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/modificar usuario.png"))); // NOI18N
        btnModificarEnfermera.setText("Modificar Enfermera");
        btnModificarEnfermera.setContentAreaFilled(false);
        btnModificarEnfermera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarEnfermera.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnModificarEnfermera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificarEnfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarEnfermeraMouseClicked(evt);
            }
        });
        btnModificarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEnfermeraActionPerformed(evt);
            }
        });

        btnAgregarEnfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/agregar usuario.png"))); // NOI18N
        btnAgregarEnfermera.setText("Agregar Enfermera");
        btnAgregarEnfermera.setContentAreaFilled(false);
        btnAgregarEnfermera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarEnfermera.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAgregarEnfermera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarEnfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarEnfermeraMouseClicked(evt);
            }
        });

        btnBorrarEnfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/eliminar_1.jpg"))); // NOI18N
        btnBorrarEnfermera.setText("Eliminar Enfermera");
        btnBorrarEnfermera.setContentAreaFilled(false);
        btnBorrarEnfermera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrarEnfermera.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnBorrarEnfermera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBorrarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarEnfermeraActionPerformed(evt);
            }
        });

        btnModfiDiagnostico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/modificar.png"))); // NOI18N
        btnModfiDiagnostico.setText("Modificar Diagnostico");
        btnModfiDiagnostico.setContentAreaFilled(false);
        btnModfiDiagnostico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModfiDiagnostico.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnModfiDiagnostico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModfiDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModfiDiagnosticoActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarEnfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(btnaddDiag)
                        .addGap(8, 8, 8)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnModificarEnfermera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar_Enfermera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarEnfermera))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnModfiDiagnostico)
                        .addGap(52, 52, 52)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegresar)
                            .addComponent(btnEliminarDiagnstico))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnModificarEnfermera))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnConsultar_Enfermera)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnBorrarEnfermera))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAgregarEnfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnaddDiag)
                    .addComponent(btnModfiDiagnostico)
                    .addComponent(btnEliminarDiagnstico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarEnfermeraActionPerformed
        // TODO add your handling code here:
        Eliminar_Enfermera EE= new Eliminar_Enfermera();
        EE.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBorrarEnfermeraActionPerformed

    private void btnModfiDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModfiDiagnosticoActionPerformed
        // TODO add your handling code here:
        Modificar_Diagnostico MD = new Modificar_Diagnostico();
        MD.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModfiDiagnosticoActionPerformed

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
            Principal_administrador PA=new Principal_administrador();
        PA.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnAgregarEnfermeraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarEnfermeraMouseClicked
        // TODO add your handling code here:
        Agregar_Enfermera AE=new Agregar_Enfermera();
        AE.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgregarEnfermeraMouseClicked

    private void btnModificarEnfermeraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarEnfermeraMouseClicked
        // TODO add your handling code here:
        Modificar_Enfermera ME=new Modificar_Enfermera();
        ME.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnModificarEnfermeraMouseClicked

    private void btnConsultar_EnfermeraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultar_EnfermeraMouseClicked
        // TODO add your handling code here:
        Consultar_Enfermera C =new Consultar_Enfermera();
        C.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnConsultar_EnfermeraMouseClicked

    private void btnaddDiagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddDiagMouseClicked
        try {
            // TODO add your handling code here:
            Agregar_Diagnostico AD= new Agregar_Diagnostico();
            AD.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Opciones_administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnaddDiagMouseClicked

    private void btnModificarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEnfermeraActionPerformed
        // TODO add your handling code here:
        Modificar_Diagnostico MD= new Modificar_Diagnostico();
        MD.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModificarEnfermeraActionPerformed

    private void btnEliminarDiagnsticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDiagnsticoActionPerformed
        // TODO add your handling code here:

        try {
          Eliminar_Diagnostico   ED = new Eliminar_Diagnostico();
            ED.setVisible(true);
        dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Opciones_administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_btnEliminarDiagnsticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones_administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEnfermera;
    private javax.swing.JButton btnBorrarEnfermera;
    private javax.swing.JButton btnConsultar_Enfermera;
    private javax.swing.JButton btnEliminarDiagnstico;
    private javax.swing.JButton btnModfiDiagnostico;
    private javax.swing.JButton btnModificarEnfermera;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnaddDiag;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
